package mp.redditwalls.design

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// custom colors
val secondaryWhite = Color.White.copy(alpha = 0.80f)
val imageBackgroundGradient = Brush.verticalGradient(
    colors = listOf(Color.Transparent, Color(0x99000000))
)

// generated colors
val md_theme_light_primary = Color(0xFFC00001)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD4)
val md_theme_light_onPrimaryContainer = Color(0xFF410000)
val md_theme_light_secondary = Color(0xFFAD3300)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onSecondaryContainer = Color(0xFF3A0B00)
val md_theme_light_tertiary = Color(0xFFAC331D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD3)
val md_theme_light_onTertiaryContainer = Color(0xFF3E0400)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2F1400)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2F1400)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857370)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE3)
val md_theme_light_inverseSurface = Color(0xFF4E2600)
val md_theme_light_inversePrimary = Color(0xFFFFB4A8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFC00001)

val md_theme_dark_primary = Color(0xFFFFB4A8)
val md_theme_dark_onPrimary = Color(0xFF690000)
val md_theme_dark_primaryContainer = Color(0xFF930000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_secondary = Color(0xFFFFB59E)
val md_theme_dark_onSecondary = Color(0xFF5E1700)
val md_theme_dark_secondaryContainer = Color(0xFF842500)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_tertiary = Color(0xFFFFB4A5)
val md_theme_dark_onTertiary = Color(0xFF650B00)
val md_theme_dark_tertiaryContainer = Color(0xFF8A1B07)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2F1400)
val md_theme_dark_onBackground = Color(0xFFFFDCC4)
val md_theme_dark_surface = Color(0xFF2F1400)
val md_theme_dark_onSurface = Color(0xFFFFDCC4)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF2F1400)
val md_theme_dark_inverseSurface = Color(0xFFFFDCC4)
val md_theme_dark_inversePrimary = Color(0xFFC00001)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A8)


val seed = Color(0xFFE9190F)